sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '12'
before_install:
  - npm i
before_script:
  - npm prune
script:
  - npm run build
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"